
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <inttypes.h>
#include <stdbool.h>

#include "core.h"

/* Main program. */
int main(void) {
  RCC->AHB4ENR |= RCC_AHB4ENR_GPIOEEN;
  GPIOE->MODER &= ~(0x3 << 2);
  GPIOE->MODER |= (0x1 << 2);
  GPIOE->OTYPER &= ~(1 << 1);

  while (1) {
    GPIOE->ODR |= (1 << 1);
  }
}
